name: Bug report
description: Report Voiid Countdown Timer bugs here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: toproduce
    attributes:
      label: "Do you know how you reproduced the bug?"
      description: 'Tell us the steps to follow to review it. You can include videos for much more detail!'
    validations:
      required: true

  - type: dropdown
    id: vcttype
    attributes:
      label: "What type of Voiid Countdown Timer build does it happen in?"
      options:
        - Datapack (V1)
        - Plugin (V2)
    validations:
      required: true

  - type: input
    id: vtcversion
    attributes:
      label: "Voiid Countdown Timer version"
      placeholder: "e.g. 1.3"
    validations:
      required: true

  - type: input
    id: mcversion
    attributes:
      label: "Minecraft version"
      placeholder: "e.g. 1.21.6"
    validations:
      required: true
