main: voiidstudios.vct.VoiidCountdownTimer
name: VoiidCountdownTimer
version: 2.1.0-a1
codename: nobelium
authors: [Voiid Studios]
api-version: 1.13
softdepend: [PlaceholderAPI]
folia-supported: true

commands:
  voiidcountdowntimer:
    description: Main command of Voiid Countdown Timer
    aliases:
      - vct