main: voiidstudios.vct.VoiidCountdownTimer
name: VoiidCountdownTimer
version: 2.0.2
codename: astro
authors: [Voiid Studios]
api-version: 1.21
softdepend: [PlaceholderAPI, FastAsyncWorldEdit, WorldEdit]

# Paper will auto-provide these libraries at runtime (Spigot ignores this key)
libraries:
  - net.kyori:adventure-text-serializer-gson:4.24.0

commands:
  voiidcountdowntimer:
    description: Main command of Voiid Countdown Timer
    aliases:
      - vct

permissions:
  voiidcountdowntimer.freeze.bypass:
    description: Allows a player to bypass global freeze restrictions
    default: false